version: '3.8'

services:
  api:
    build: .
    command: uvicorn src.api.endpoints:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - kafka
      - mlflow

  streaming:
    build: .
    command: python -m src.streaming.consumer
    volumes:
      - .:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka

  train:
    build: .
    command: python -m src.models.train
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./mlflow/artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - PYTHONPATH=/app
    depends_on:
      - mlflow

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5001"
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5001 
      --backend-store-uri sqlite:///mlflow.db 
      --artifacts-destination /mlflow/artifacts 
      --serve-artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5001
    volumes:
      - ./mlflow/artifacts:/mlflow/artifacts
      - ./mlflow/db:/mlflow/db

  playground:
    build: .
    command: streamlit run src/streamlit_playground/playground.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./mlflow/artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - PYTHONPATH=/app
    depends_on:
      - mlflow
